---
title: "Burrow microclimate code"
author: "Cerren Richards"
date: "02/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


## Combine all the files

- Combine all the separate burrow .csv files
- Correct the data and times
- Match the metadata

```{r}
# Read in metadata and corrected date and times for the data
metadata <- read.csv("metadata.csv")
datetime <- read.csv("dateandtimes.csv")


# Read in all the files at once
# Make a list of all the .csv files
files <- list.files(pattern="*.csv")

# First apply read.csv, then rbind
temps <- do.call(rbind, lapply(files, function(x) read.csv(x, stringsAsFactors = FALSE)))

# Remove the origional date and times because they are in different formats
temps$Date <- NULL 
temps$Time <- NULL

# Join the corrected date and times to the `temps` dataframe
temps <- cbind(temps, datetime)

# Join the metadata to the `temps` dataframe
temps <- left_join(temps, metadata, by = "Name")

# Join the date and time columns and specify the format
temps$datetime <- as.POSIXct(paste(temps$Date, temps$Time), format="%d-%m-%Y %H:%M:%S")

```


## Plot over the whole study 

Create a plot showing the mean and standard deviation temperature variation through the season 

A good resource for timeseries plotting on the xaxis:
https://www.r-graph-gallery.com/279-plotting-time-series-with-ggplot2.html

```{r}

# Summarise the mean temperature and standard deviation for inside and outside the burrows
season_mean_temp <- temps %>%
  group_by(Location, datetime) %>%
  summarise(mean = mean(Temperature), sd = sd(Temperature),
            n = n(), se = sd/sqrt(n))


# Plot Inside temperature trend
ggplot(data = filter(season_mean_temp, Location == "Inside"), aes(x = datetime, y = mean))+
  geom_line()+
  geom_ribbon(aes(ymin=mean-sd, ymax=mean+sd), alpha = 0.25)+
  theme_bw(base_size = 15)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  xlab("Date") + ylab("Temperature (°C)")+
  theme(axis.title.y = element_text(vjust = 3))+
  theme(axis.title.x = element_text(vjust = -1))+
  scale_x_datetime(date_breaks = "10 days", date_labels = "%d %b %Y")



# Plot Outside temperature 
ggplot(data = filter(season_mean_temp, Location == "Outside"), aes(x = datetime, y = mean))+
  geom_line()+
  geom_ribbon(aes(ymin=mean-sd, ymax=mean+sd), alpha = 0.25)+
  theme_bw(base_size = 15)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  xlab("Date") + ylab("Temperature (°C)")+
  theme(axis.title.y = element_text(vjust = 3))+
  theme(axis.title.x = element_text(vjust = -1))+
  scale_x_datetime(date_breaks = "10 days", date_labels = "%d %b %Y")



# Facet wrap version of temperature trend
ggplot(data = season_mean_temp, aes(x = datetime, y = mean))+
  geom_line()+
  geom_ribbon(aes(ymin=mean-sd, ymax=mean+sd), alpha = 0.25)+
  theme_bw(base_size = 15)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  xlab("Date") + ylab("Temperature (°C)")+
  theme(axis.title.y = element_text(vjust = 3))+
  theme(axis.title.x = element_text(vjust = -1))+
  scale_x_datetime(date_breaks = "10 days", date_labels = "%d %b")+
  facet_wrap(~Location, scales = "free_y", ncol = 1, nrow = 2)+
  theme(strip.text.x = element_text(size = 15, color = "white"), 
          strip.background = element_rect(fill="black"))

```

## Plot for mean temp

```{r}

# Summarise the mean temperature and standard deviation for inside and outside the burrows
mean_temp <- temps %>%
  group_by(Location, Hour) %>%
  summarise(mean = mean(Temperature), sd = sd(Temperature),
            n = n(), se = sd/sqrt(n))


# Plot
ggplot(mean_temp, aes(x = Hour, y = mean, group = Location))+
  geom_line()+
  geom_pointrange(aes(ymin=mean-sd, ymax=mean+sd))+
  geom_point(size = 3,shape = 21, aes(fill = Location))+
  scale_fill_manual(values=c('black','white'))+
  theme_bw(base_size = 15)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  xlab("Time of Day (h)") + ylab("Temperature (°C)")+
  scale_x_continuous(breaks=seq(0,23,2))+
  theme(axis.title.y = element_text(vjust = 3))+
  theme(axis.title.x = element_text(vjust = -1)) +
  theme(legend.position = c(0.15, 0.75))


```

## Plot the temperature variation between burrows

```{r}

# Plot - colours (not good)
ggplot(data = filter(temps, Location == "Inside"), aes(x = datetime, y = Temperature))+
  geom_line(aes(colour = Burrow))+
  theme_bw(base_size = 15)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  xlab("Date") + ylab("Temperature (°C)")+
  theme(axis.title.y = element_text(vjust = 3))+
  theme(axis.title.x = element_text(vjust = -1))+
  scale_x_datetime(date_breaks = "10 days", date_labels = "%d %b %Y")


# Calculate the mean temperature and standard deviation for each burrow
burrows <- filter(temps, Location == "Inside") %>%
  group_by(Burrow) %>%
  summarise(burrowmean = mean(Temperature), burrowsd = sd(Temperature))

# Join to the main dataframe
temps <- left_join(temps, burrows)

# Plot timeseries with mean
ggplot(data = filter(temps, Location == "Inside"), aes(x = datetime, y = Temperature))+
  geom_line()+
  theme_bw(base_size = 15)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  xlab("Date") + ylab("Temperature (°C)")+
  theme(axis.title.y = element_text(vjust = 3))+
  theme(axis.title.x = element_text(vjust = -1))+
  scale_x_datetime(date_breaks = "10 days", date_labels = "%d %b %Y")+
  geom_hline(aes(yintercept = burrowmean), colour = "red", size = 1)+
  facet_wrap(~Burrow, nrow = 1)
  


# Plot mean and sd
ggplot(burrows, aes(x = Burrow, y = burrowmean))+
  geom_pointrange(aes(ymin=burrowmean-burrowsd, ymax=burrowmean+burrowsd))+
  geom_point(size = 3,shape = 21)+
  theme_bw(base_size = 15)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  xlab("Burrow") + ylab("Mean Temperature (°C)")+
  #scale_x_continuous(breaks=seq(0,23,2))+
  theme(axis.title.y = element_text(vjust = 3))+
  theme(axis.title.x = element_text(vjust = -1))


```



